### ISSUE TITLE
[NEWBIE question] I can't get brackets-debugger to work.

### ISSUE THREAD

**Issue by qbicsky** [jdiehl/brackets-debugger#48]
Hi!
I am a newbie at the beginning of learning to code.
I was debugging code in Chrome Developer Tools but since it breaks connection with Brackets, I was looking for some alternative which would work with Live Preview. And here I am.
After installing extension (to user's directory directly cause linking from disabled didn't want to work for some reason), in my Brackets,  console of the extension appears. In the console there is blue text: [object Object]. When I click on the gutter unfortunatelly nothing happens. There is no breakpoint. Could you please help me to get brackets-debugger to work.

**Comment by jdiehl** [comment]
This extension is deprecated and will not work. I recommend that you try out Theseus: https://github.com/adobe-research/theseus

**Comment by qbicsky** [comment]
Thanks for your quick reply.
I was trying Theseus. For some reson it won't show me anything in console. I see callback counters, but no data in console.
